name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build JAR with Gradle
        run: ./gradlew clean build

      - name: Build Docker Image
        run: |
          docker build -t us-central1-docker.pkg.dev/taiyuken/taiyuken/taiyuken-back-app .

      - name: Push Docker image to Artifact Registry
        run: |
          docker push us-central1-docker.pkg.dev/taiyuken/taiyuken/taiyuken-back-app

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy taiyuken-back-app \
            --image=us-central1-docker.pkg.dev/taiyuken/taiyuken/taiyuken-back-app \
            --region=us-central1 \
            --platform=managed \
            --allow-unauthenticated